Homework 17 Ilya
NET16-Homeworks/Homework_Module17 pull request #1
Opened 2022-09-11 16:22 UTC by BFipe

В общем, сначала я ничего не понял, потом ничего не понял. Начал делать. Очнулся, когда работа была готова. Как это работает - я не знаю, но оно работает

2022-09-12 11:31 UTC, PushMeNow requested changes

2022-09-12 11:31 UTC, PushMeNow commented on Homework_Module17/Homework_Module17/Components/GetUserViewComnponent.cs
> +        UserService userService = new UserService();
Не забывай про модификаторы доступа. Их рекомендуется не пропускать.
Проставь везде модификаторы, где ты пропустил.

2022-09-12 11:31 UTC, PushMeNow commented on Homework_Module17/Homework_Module17/Components/GetUserViewComnponent.cs
> +            return $"Name: {user.Name}, Country: {user.Country}, Sex: {user.Sex}, Is Married: {user.IsMarried}";
Немного исправил доку с домашним заданием. Я тут хотел, чтобы было сделано через компонент с одной стороны и представление с другой. Т.е. тут должен быть вызов View и передача в него модели юзера, а на представлении должна уже быть конкатенация.

2022-09-12 11:31 UTC, PushMeNow commented on Homework_Module17/Homework_Module17/Controllers/UserController.cs
> +            return View(userService.GetUsers());
Получение юзеров лучше вынести в отдельную переменную. Не нужно лепить это в одну линию вызова.

2022-09-12 11:31 UTC, PushMeNow commented on Homework_Module17/Homework_Module17/Controllers/UserController.cs
> +        }
Мда... Это мой фэйл. Я поправил доку. Удали плз.

2022-09-12 11:31 UTC, PushMeNow commented on Homework_Module17/Homework_Module17/Controllers/UserController.cs
> +        }
Зачем?

2022-09-12 11:31 UTC, PushMeNow commented on Homework_Module17/Homework_Module17/Services/UserService.cs
> +
Что это за пустое место?

2022-09-12 11:31 UTC, PushMeNow commented on Homework_Module17/Homework_Module17/ViewModels/UserViewModel.cs
> +    public enum sex
Sex с большой буквы и вынеси в отдельный файл

2022-09-12 11:31 UTC, PushMeNow commented on Homework_Module17/Homework_Module17/ViewModels/UserViewModel.cs
> +    public record class UserViewModel
Какой смысл тут в record?

2022-09-12 11:31 UTC, PushMeNow commented on Homework_Module17/Homework_Module17/Views/User/Index.cshtml
> +@{foreach (var user in Model)
зачем тут фигурные скобки перед foreach?

2022-09-12 11:31 UTC, PushMeNow commented on Homework_Module17/Homework_Module17/Views/_ViewImports.cshtml
> +@using Homework_Module17.Controllers
Зачем тут подгружать Homework_Module17.Controllers и Homework_Module17.Services?

2022-09-12 12:44 UTC, BFipe commented on Homework_Module17/Homework_Module17/Components/GetUserViewComnponent.cs
> +            return $"Name: {user.Name}, Country: {user.Country}, Sex: {user.Sex}, Is Married: {user.IsMarried}";
то есть, я должен сделать return View(user) ?

2022-09-13 07:36 UTC, im-kborovik approved these changes

2022-09-13 10:16 UTC, closed without merging