Module17 Homework
NET16-Homeworks/Homework_Module17 pull request #7
Opened 2022-09-21 17:14 UTC by kricobelka

Please review

2022-09-23 08:58 UTC, im-kborovik requested changes

2022-09-23 08:58 UTC, im-kborovik commented on Homework_Module17/Homework_Module17/Views/User/DeleteUser.cshtml
> +﻿@model UserViewModel
Зачем тебе тут указывать модель?

2022-09-26 20:42 UTC, kricobelka commented on Homework_Module17/Homework_Module17/Views/User/DeleteUser.cshtml
> +﻿@model UserViewModel
экшен в контроллере же нужно передать в модель, чтобы представление выполнилось

если нет, объясни, пожалуйста, почему она не нужна

2022-09-26 20:47 UTC, kricobelka commented on Homework_Module17/Homework_Module17/Views/User/GetUsers.cshtml
> +        ViewBag.Title("GetUsers field");
@im-kborovik  еще вопрос есть: тут почему-то при написании вьюбэг высвечивает ошибку во вьюхе GetUsers. Поэтому я закомментила

Почему так происходит? в других вьюшках все ок
вот пример
![image](https://user-images.githubusercontent.com/106872837/192377173-a5bc1195-20f3-4acf-9576-b0c27b66b6ae.png)

2022-09-27 10:50 UTC, im-kborovik commented on Homework_Module17/Homework_Module17/Views/User/DeleteUser.cshtml
> +﻿@model UserViewModel
Дело в том, что мы модель на этом представлении никак не используем. Более того, мы эту модель и не передаём обратно в контроллер, поэтому я не вижу смысла, почему она должна здесь быть.

2022-09-27 10:54 UTC, im-kborovik commented on Homework_Module17/Homework_Module17/Views/User/GetUsers.cshtml
> +        ViewBag.Title("GetUsers field");
Я не очень понимаю, что ты хочешь здесь сделать. Если ты хочешь в поле Title записать значение, то это делается так:
`ViewBag.Title = "GetUsers field"`.
Title это же не метод, это свойство объекта, а ты как раз пытаешься его вызвать как метод.

2022-09-28 19:54 UTC, kricobelka commented on Homework_Module17/Homework_Module17/Views/User/DeleteUser.cshtml
> +﻿@model UserViewModel
Ок спасибо  за коммент

2022-09-28 19:55 UTC, kricobelka commented on Homework_Module17/Homework_Module17/Views/User/GetUsers.cshtml
> +        ViewBag.Title("GetUsers field");
Точно
Тупанула

2022-09-28 19:56 UTC, kricobelka commented on Homework_Module17/Homework_Module17/Views/User/DeleteUser.cshtml
> +﻿@model UserViewModel
Чтобы изменить, мне нужно заходить в вижу и путать снова или у нас  особый способ? @im-kborovik

2022-10-16 12:05 UTC, im-kborovik approved these changes

2022-10-16 12:05 UTC, closed without merging